#!/usr/bin/env python3

"""
Executable for heterogeneous_groups
"""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent / "lib"))

import works.asm.heterogeneous_groups.grouping as g  # pylint: disable=import-error,wrong-import-position

print(g.Weight(1))
